install:
  # Using '-y' and 'refreshenv' as a workaround to:
  # https://github.com/haskell/cabal/issues/3687
  - choco install -y ghc --version 8.0.1 > NUL
  - refreshenv
  - curl -o cabal.zip --silent https://www.haskell.org/cabal/release/cabal-install-1.24.0.0/cabal-install-1.24.0.0-x86_64-unknown-mingw32.zip
  - 7z x -bd cabal.zip
  - cabal --version
  - cabal update

build_script:
  - cd Cabal
  - ghc --make -threaded -i -i. Setup.hs -Wall -Werror -XRank2Types -XFlexibleContexts

  # 'echo "" |' works around an AppVeyor issue:
  # https://github.com/commercialhaskell/stack/issues/1097#issuecomment-145747849
  - echo "" | ..\cabal install --only-dependencies --enable-tests

  - Setup configure --user --ghc-option=-Werror --enable-tests
  - Setup build
  - Setup test --show-details=streaming --test-option=--hide-successes
  - Setup install
  - cd ..\cabal-testsuite
  - ghc --make -threaded -i Setup.hs -package Cabal-1.25.0.0
  - echo "" | ..\cabal install --only-dependencies --enable-tests
  - Setup configure --user --ghc-option=-Werror --enable-tests
  - Setup build
  # Must install the test suite, so that our GHCi invocation picks it up
  - Setup install
  # Copy the setup script into the spot cabal-tests expects it
  - mkdir dist\setup
  - cp Setup.exe dist\setup
  - dist\build\cabal-tests\cabal-tests.exe -j3
  # - Setup test --show-details=streaming --test-option=--hide-successes
  - cd ..\cabal-install
  - ghc --make -threaded -i -i. Setup.hs -Wall -Werror
  - echo "" | ..\cabal install happy
  - echo "" | ..\cabal install --only-dependencies --enable-tests
  - ..\cabal configure --user --ghc-option=-Werror --enable-tests
  - ..\cabal build
  # update package index again, this time for the cabal under test
  - dist\build\cabal\cabal.exe update
  - ..\cabal test unit-tests --show-details=streaming --test-option=--pattern=!FileMonitor --test-option=--hide-successes
  - ..\cabal test integration-tests --show-details=streaming --test-option=--pattern=!exec --test-option=--hide-successes
  - ..\cabal test integration-tests2 --show-details=streaming --test-option=--hide-successes
  - ..\cabal test solver-quickcheck --show-details=streaming --test-option=--hide-successes --test-option=--quickcheck-tests=1000
